// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvmBohqmLhgAv0bZSRg-hUVcWAPDxqQHc',
    appId: '1:189797188339:web:6b04cc7c4f16749793ed86',
    messagingSenderId: '189797188339',
    projectId: 'careclimate-95ea3',
    authDomain: 'careclimate-95ea3.firebaseapp.com',
    databaseURL: 'https://careclimate-95ea3-default-rtdb.firebaseio.com',
    storageBucket: 'careclimate-95ea3.appspot.com',
    measurementId: 'G-887LSKQ5X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs2d7P41qBnxYi2ZAkrGGWnX4XXV29fxk',
    appId: '1:189797188339:android:e761842cc4b47c1993ed86',
    messagingSenderId: '189797188339',
    projectId: 'careclimate-95ea3',
    databaseURL: 'https://careclimate-95ea3-default-rtdb.firebaseio.com',
    storageBucket: 'careclimate-95ea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2rAmhEZWTrYHvdafNxKl-Cw79ZmuzjcU',
    appId: '1:189797188339:ios:2bde9cc4ad2ef30b93ed86',
    messagingSenderId: '189797188339',
    projectId: 'careclimate-95ea3',
    databaseURL: 'https://careclimate-95ea3-default-rtdb.firebaseio.com',
    storageBucket: 'careclimate-95ea3.appspot.com',
    androidClientId: '189797188339-6ov0ro315gd6ffmm03hcsic1roc8ougb.apps.googleusercontent.com',
    iosClientId: '189797188339-qcjfa7n9a9574o5fcap2bufqv4dqdsua.apps.googleusercontent.com',
    iosBundleId: 'com.example.careclimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2rAmhEZWTrYHvdafNxKl-Cw79ZmuzjcU',
    appId: '1:189797188339:ios:2bde9cc4ad2ef30b93ed86',
    messagingSenderId: '189797188339',
    projectId: 'careclimate-95ea3',
    databaseURL: 'https://careclimate-95ea3-default-rtdb.firebaseio.com',
    storageBucket: 'careclimate-95ea3.appspot.com',
    androidClientId: '189797188339-6ov0ro315gd6ffmm03hcsic1roc8ougb.apps.googleusercontent.com',
    iosClientId: '189797188339-qcjfa7n9a9574o5fcap2bufqv4dqdsua.apps.googleusercontent.com',
    iosBundleId: 'com.example.careclimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvmBohqmLhgAv0bZSRg-hUVcWAPDxqQHc',
    appId: '1:189797188339:web:e4a3be33334f173593ed86',
    messagingSenderId: '189797188339',
    projectId: 'careclimate-95ea3',
    authDomain: 'careclimate-95ea3.firebaseapp.com',
    databaseURL: 'https://careclimate-95ea3-default-rtdb.firebaseio.com',
    storageBucket: 'careclimate-95ea3.appspot.com',
    measurementId: 'G-R467H1VT13',
  );
}
